services:
  - type: web
    name: ocr-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    plan: free
